spring:
  application:
    name: ServicioTransacciones
  datasource:
    url: jdbc:postgresql://localhost:5442/db_transacciones
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
# Para cargar data.sql al inicio
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always
server:
  port: 8087
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
